name: Generate Football Predictions

on:
  schedule:
    # Run every day at 7 AM UTC (8 AM UK time)
    - cron: '0 7 * * *'
  workflow_dispatch: # Allows manual running

jobs:
  generate-predictions:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
    
    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: 📦 Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: 🎯 Generate predictions
      env:
        FOOTBALL_DATA_TOKEN: ${{ secrets.FOOTBALL_DATA_TOKEN }}
        ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
      run: |
        cd scripts
        python generate_predictions.py
    
    - name: 📤 Commit and push changes
      run: |
        git config --local user.email "predictions@footballpredictor.com"
        git config --local user.name "Football Predictor Bot"
        git add data/predictions.json data/tips.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🤖 Auto-update predictions $(date +'%Y-%m-%d %H:%M:%S')"
          git push
        fi
